name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: ahleighton
  GITHUB_REPOSITORY: ahleighton/OE-ephys-course
  GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}

on:
  push:
    branches: [ docs-config ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #runs-on: ubuntu-18.04-huge # for local with act

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies 📦
        run: |
          pip install pipenv
          pipenv install
      - name: Build docs 🔧
        run: pipenv run make html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: docs-config # The branch the action should deploy to.
          folder: docs/html # The folder the action should deploy.

      - name: Test links 🧪
        run: pipenv run make linkcheck
